### ISSUE TITLE
gentoo ebuilds

### ISSUE THREAD

**Issue by uu** [yandex/odyssey#13]
Here is a live ebuild for gentoo in [ubuilds](https://github.com/uu/ubuilds/tree/master/dev-db/odyssey) overlay. Waiting for the first release :wink:

**Comment by uu** [comment]
got 1.0

**Comment by x4m** [comment]
Hi! I think we will have 1.1 soon :)

**Comment by uu** [comment]
[alpine version](https://gitlab.alpinelinux.org/alpine/aports/commit/7151537ff2bea878c0e6e792c7f0385908cfc8c4) has been packaged as well
