### ISSUE TITLE
Can odyssey be used in listen/notify?

### ISSUE THREAD

**Issue by dmitryikh** [yandex/odyssey#130]
Can we use odyssey in order to reduce number of Postgres connections in case when clients use [listen](https://www.postgresql.org/docs/9.1/sql-listen.html)/[notify](https://www.postgresql.org/docs/9.1/sql-notify.html)?

**Comment by pmwkaa** [comment]
It should work with session pooling for sure

**Comment by dmitryikh** [comment]
Can briefly describe or point to documentation about how to do this?

**Comment by x4m** [comment]
You can setup user who have pool mode "session"
See https://github.com/yandex/odyssey/blob/master/odyssey.conf#L448

**Comment by dmitryikh** [comment]
Thanks for clarification!

Am I right, that if I have 100 clients who needs permamently listen notifications then I will occupy 100 connections to postgres and won't gain using odyssey at all?

**Comment by x4m** [comment]
@dmitryikh yes
