### ISSUE TITLE
Show user in connection error message

### ISSUE THREAD

**Issue by georgthegreat** [yandex/odyssey#138]
If wrong username was passed in connection string, Odyssey will respond with the following error message:
```
ERROR:  odyssey: cd0cc8a7b6adf: user blocked
```

It would be nice to have username given in this message. This could simplify debugging in some cases.

**Comment by solozobov** [comment]
continuing idea of @georgthegreat
Also I think it would be better if we distinguish error messages of three kinds:
1. "unknown user '%username%'", when wrong username was passed in connection string
2. "user '%username%' is not authorized to connect to database '%database%'" when user don't have permission to connect to specified database

**Comment by x4m** [comment]
Also, in the same task we need to improve messages about connection limits:
1. When overall connection limit reached
2. When pool connection limit reached
3. When active connections limit reached

Currently, errors vary in politeness and punctuation. We need more descriptive and clear messages here.

**Comment by nickitat** [comment]
Kind of what @solozobov mentioned in the second point. If you try to connect to non-existing database you will get the same "user blocked" error message.

**Comment by x4m** [comment]
@nickitat @georgthegreat @solozobov Can I ask you to review error messages in linked pull request? Just If you have some spare time..
