### ISSUE TITLE
build fails on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by MichaelDBA** [yandex/odyssey#14]
Followed the instructions for downloading and installing:

> git clone git://github.com/yandex/odyssey.git
> cd odyssey
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=Release ..
> make

The error log shows this:
> /usr/bin/ld:  cannot find -lpthreads

Wondering if it should be **lpthread**, not **lpthreads**...

It fails on the cmake line:

> # cmake -DCMAKE_BUILD_TYPE=Release ..
> -- Use shipped libmachinarium: /root/odyssey/third_party/machinarium
> -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
> -- Use shipped libshapito: /root/odyssey/third_party/shapito
> --
> -- Odyssey (version: f67e0b8 release)
> --
> -- CMAKE_BUILD_TYPE: Release
> -- BUILD_DEBIAN:     OFF
> --
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> OPENSSL_CRYPTO_LIBRARY (ADVANCED)
>     linked by target "odyssey" in directory /root/odyssey/sources
>     linked by target "odyssey_stress" in directory /root/odyssey/stress
>     linked by target "odyssey_test" in directory /root/odyssey/test
> OPENSSL_INCLUDE_DIR (ADVANCED)
>    used as include directory in directory /root/odyssey
>    used as include directory in directory /root/odyssey
>    used as include directory in directory /root/odyssey
>    used as include directory in directory /root/odyssey/sources
>    used as include directory in directory /root/odyssey/stress
>    used as include directory in directory /root/odyssey/test
> OPENSSL_SSL_LIBRARY (ADVANCED)
>     linked by target "odyssey" in directory /root/odyssey/sources
>     linked by target "odyssey_stress" in directory /root/odyssey/stress
>     linked by target "odyssey_test" in directory /root/odyssey/test
> 
> -- Configuring incomplete, errors occurred!
> See also "/root/odyssey/build/CMakeFiles/CMakeOutput.log".
> See also "/root/odyssey/build/CMakeFiles/CMakeError.log".

**Comment by pmwkaa** [comment]
OpenSSL version < 1.1 is required to build. 

maybe  `sudo apt-get install libssl1.0-dev` would help.

**Comment by MichaelDBA** [comment]
1.0 is installed:

> # dpkg -l | grep libssl
> ii  libssl1.0.0:amd64                                     1.0.1f-1ubuntu2.25                                  amd64        Secure Sockets Layer toolkit - shared libraries
> ii  libssl1.0.0:i386                                      1.0.1f-1ubuntu2.25                                  i386         Secure Sockets Layer toolkit - shared libraries
>

**Comment by pmwkaa** [comment]
Usually there are separated packages for the shared library and development files. Package with openssl development files is required.

**Comment by MichaelDBA** [comment]
ahh, needed libssl-dev.  That worked!  Thanks.
