### ISSUE TITLE
are prepared statements supported in transaction pooling mode?

### ISSUE THREAD

**Issue by bashtanov** [yandex/odyssey#16]
are prepared statements supported in transaction pooling mode?

**Comment by pmwkaa** [comment]
No, this is not supported currently. Situation is the same as with PgBouncer, maybe some wraparounds will happen in future. Are you looking for this feature?

**Comment by bashtanov** [comment]
Thanks, yes, for me it's the most discouraging problem with standalone postgresql poolers. I'm not quite sure what should the implementation look like. Deallocating and re-preparing everything on server connection reuse seem way too much overhead to me.

Under certain assumptions (prepared statements named based on hashes of the SQL they code; variables like `search_path` or `enable_sort` remain stable) the pooler could somehow track whether a server session has a query prepared and issue PREPARE command on demand only if necessary, and perhaps even DEALLOCATE them if worried about backend memory usage. Even if the assumptions don't hold it'd still be possible to track all that stuff. Maybe it's all too complicated to keep things lightweight and lock-free though -- we'll have to deeper inspect the traffic, and to maintain a global map of prepared statements.

**Comment by davidfetter** [comment]
If you know which statements you want prepared, there's always the [preprepare](https://github.com/dimitri/preprepare) project.

**Comment by thedrow** [comment]
@omarkilani But once it is done, how big is the overhead in maintaining the implementation?
Also, just to get an idea of how much effort it takes, how many LOC are we talking about?

**Comment by omarkilani** [comment]
@thedrow pgbouncer has been around for 11 years. No one has bothered to implement that feature either publicly or privately AFAIK.

Note that I'm talking about maintaining a prepared statement cache or whatever inside the daemon.

pgbouncer supports one shot prepared statements in transaction pooling mode. I'm assuming odyssey does too, but I don't think it did until this PR: https://github.com/yandex/odyssey/pull/20

**Comment by patsevanton** [comment]
Really looking forward of prepared statements supported

**Comment by bolknote** [comment]
+100500 to prepared statements!

**Comment by vivan-niche** [comment]
This is a roadblock for us as well.  Our use case for a connection pooler is multiple developers using an on-premise database server, and our clients all use long-lived connections and prepared statements.  Implementing a connection pooler would require us to rewrite sql logic in 30+ repositories to strip out prepared statements.

**Comment by alokob** [comment]
prepareThreshold=0 also doe not help.

**Comment by CySlider** [comment]
I wonder, can I use prepared statements (in transaction mode) as long as they are prepared and used in the same transaction?

so:

1. begin transaction
2. so some sql
3. prepare statement
4. use prepared statement a few time
5. do some other sql stuff
6. commit

Will this at least work?

**Comment by x4m** [comment]
@CySlider until transaction is finished client is bound to server connection. There is no problem with this scenario.

Release 1.3 will also add support for protocol-level prepared statements. You will be able :
1. Parse statement X
2. Bind X to parameter values (execute). Commit.
3. Bind X to parameter values (execute) again. Commit.
4. Bind X to parameter values (execute) again. Commit.

So that prepared statement X will survive through transaction boundaries.

Thanks!

**Comment by kneeraj** [comment]
Hi @x4m , Looks like 1.3 is already out. This may be already working now?

**Comment by x4m** [comment]
Yes, please use [reserve_prepared_statements](https://github.com/yandex/odyssey/blob/master/config-examples/odyssey-dev.conf#L88) to try this out. Though I haven't heard much of a feedback yet, despite some Yandex services are using this feature.

**Comment by jayant07-yb** [comment]
It seems like in reserve_prepared_statements mode; if any client wants to prepare a statement and the server finds an already prepared statement with the same name from another client; then it closes the previously prepared statement and then prepares the statement from the new client.
I was wondering about the performance.

**Comment by jayant07-yb** [comment]
I was trying to test the prepared statement but was facing issues in the build.
Can anyone help me with it?
Issue: [444](https://github.com/yandex/odyssey/issues/444)  
```
My system:  CentOS 7
GCC version 4.8.5 20150623
cmake version 3.20.0
OpenSSL version 1.0.2k-fips 26 Jan 2017
```

**Comment by x4m** [comment]
> It seems like in reserve_prepared_statements mode; if any client wants to prepare a statement and the server finds an already prepared statement with the same name from another client; then it closes the previously prepared statement and then prepares the statement from the new client. I was wondering about the performance.

No, it doesn't work that way. When the client prepares statement it's name is not given by a client. Instead some canonicalized hash name is created and associated for client's given name of statement.

**Comment by jayant07-yb** [comment]
Thanks for helping @x4m ,
Can you please help me with
1. Is this canonicalized hash name generated by odyssey or the client-side driver.
2. Is the name of the prepared statements gets replaced with this hash name or something else by odyssey before forwarding it to the server.

**Comment by x4m** [comment]
1. by Odyssey
2. yes

**Comment by jayant07-yb** [comment]
Sure,
I found this [line](https://github.com/yandex/odyssey/blob/f9a1ec21bc908ce4814b3ca2cfc7f1028204e466/sources/frontend.c#L1195) which was closing an already prepared statement that was allocated by a previous client with the same name.

**Comment by jayant07-yb** [comment]
@x4m  Does the hash value depend on the client id or just the name of the prepared statement given by the client driver?

**Comment by reshke** [comment]
Yes, it depends on client id
