### ISSUE TITLE
How does the parameter change notification work?

### ISSUE THREAD

**Issue by heckad** [yandex/odyssey#181]
I am working under supporting search_path parameter, and I need to know how do you subscribe on change aplication_name parameter on the server?

**Comment by x4m** [comment]
Hi! That sounds great.
Here you can find ```if``` that is responsible for adding or not adding host name to the ```aplication_name``` session setting.

**Comment by heckad** [comment]
Hi!
I rather talked about the `od_backend_update_parameter` method. 

```
od_backend_update_parameter backend.c:526
od_frontend_remote_server frontend.c:567
od_relay_on_packet relay.h:184
od_relay_process relay.h:220
od_relay_pipeline relay.h:279
od_relay_step relay.h:358
od_frontend_remote frontend.c:780
od_frontend frontend.c:1279
mm_scheduler_main scheduler.c:18
mm_context_runner context.c:30
<unknown> 0x0000000000000000
```
This stack was gotten when a server (connection to postgres as I understand) changed application_name var. Seems you use some event in order to find out that the `application_name` variable has changed. What kind of event is this?

**Comment by heckad** [comment]
https://github.com/yandex/odyssey/pull/183

**Comment by x4m** [comment]
od_frontend_remote_server is responsible for handling message from client. And there we handle ParameterStatus frontend message.

But, AFAIK you are interested in setting search_path via startup parameters. This happens in od_frontend_startup.
