### ISSUE TITLE
Get odyssey configuration from CLI

### ISSUE THREAD

**Issue by bukem** [yandex/odyssey#210]
Hi guys,

Is there a way to get the configuration of the current instance of Odyssey without accessing the config file?
In Pgbouncer we have `show config;` command to get the configuration, but it seems like it is not implemented in Odyssey:
```
console=> show config;
ERROR:  odyssey: c4c171e50be88: console command error: show config;
```

Thanks!

Regards, Mikhail

**Comment by x4m** [comment]
Makes sense, I think we will implement this. Or at least PR would be welcomed. Thanks for the proposal!
One caveat is that we surely will filter our credentials to mitigate security risks.

**Comment by bukem** [comment]
I'd like to help with PR, but my C level is... undefined :)

**Comment by x4m** [comment]
Don't worry. Just make it work. I'll help with merging. Or at least I'll find someone from YC to help you with your PR.
