### ISSUE TITLE
Use client password in authentication 

### ISSUE THREAD

**Issue by mo4islona** [yandex/odyssey#291]
Am i right that is not possible to use password from client for authentication for now?
And there is no way to use odyssey just as a proxy and/or connection limiter —
I must set it all db passwrods in the odyssey config explicitly?

Why? It is  because of an architecture limitation, or you just don't need that in your own usage?

What do u think about new type of authentication `pass_through`?
For example, we have a PG db `test`, user `test_user`, password `test_password`
```
database "test" {
  user default {
    authentication "block"
    storage "master_server"
    pool "session"
  }
  user "test_user" {
    authentication "pass_through"
    storage "master_server"
   
    # storage_password "IS NOT SET — WE WILL GET IT FROM CONNECTED CLIENT"
    pool "session"
   ....
  }
}
```

```bash
PGPASSWORD=test_password psql -d test -U test_user -h odyssey -p 6432
psql (13.2, server 12.3)
Type "help" for help.

test=#
```

**Comment by x4m** [comment]
Hi! Thanks for your contribution and inquiry!
It is not implemented, yet the feature would be welcomed.
As to our needs in Y.Cloud, we actually were running fine without it. In Managed PostgreSQL we just have to reload configs of pools anyway. But recently we encountered that internal installation of Greenplum would benefit from auth_query pass-trough. And right now I'm working on fixing #105. It is not exactly what you want, Odyssey will consult with pg_shadow to get authentication information. But it allows you to avoid entering all users into configs.

**Comment by mo4islona** [comment]
Thanks for quick response and great job so far.

#105 is not exactly what I want. AS I understand they use a custom table for user/pass in public scheme in some db. And I want to use standard PG users.
Yes, lookup in pg_shadow will solve the problem but it will require superuser access.
We also use Managed PostgreSQL provided by Google and have no options to do that.

I guess it all could be done without pg_shadow access isn`t it?
