### ISSUE TITLE
Listening on unix socket

### ISSUE THREAD

**Issue by iKevinShah** [yandex/odyssey#31]
Hi,

Does odyssey support listeniing on Unix sockets only. We use pgbouncer currently locally on each webserver (client) which connects to pgbouncer via socket.

I checked [odyssey configuration example](https://github.com/yandex/odyssey/blob/master/documentation/configuration.md) and saw no mention of the same.

Is it a design decision or in the pipeline for future releases ?

**Comment by pmwkaa** [comment]
Hi. Yes, I believe we could add support for it soon

**Comment by iKevinShah** [comment]
Much awaited :)

**Comment by pmwkaa** [comment]
Alright. Now it should be possible to do it. Just comment out `host` field from `listen` or `storage` section and unix socket will be used instead of tcp/ip. Socket directory can be set in `unix_socket_dir`.
