### ISSUE TITLE
Postgres 14 Pipeline Mode

### ISSUE THREAD

**Issue by marcbachmann** [yandex/odyssey#354]
Postgres 14 just got released and a new pipeline query mode landed in there.
That would drastically improve the performance of queries and is definitely worth to check out.

https://www.postgresql.org/docs/14/libpq-pipeline-mode.html

**Comment by x4m** [comment]
Hi! As far as I know latest commits of Odyssey works fine with pipeline mode. Though release 1.1 does not. We definitely need to land a new release.

**Comment by marcbachmann** [comment]
Cool. Great work

**Comment by marcbachmann** [comment]
I only saw 3 pipeline references in the code. So I wasn't sure about it. 😁 
Let's close this for now.
