### ISSUE TITLE
Odyssey performance under different workers

### ISSUE THREAD

**Issue by yanboer** [yandex/odyssey#405]
I have PostgreSQL and Odyssey installed on a 16 core 32GB host:

The PostgreSQL version and Odyssey version are as follows:
```
root@i-q1ogv86a:~/odyssey# /usr/lib/postgresql/bin/postgres --version
postgres (PostgreSQL) 11.14
root@i-q1ogv86a:~/odyssey# 
root@i-q1ogv86a:~/odyssey# build/sources/odyssey --version
odyssey (git: 2018 fade747 release)
```
I tried to use pgbench to test the performance of Odyssey under different workers and got the following results:

pgbench test command:
```
# init
pgbench -h 192.168.100.14 -p 6432 -U odyssey -s 10000 -i odyssey

# test
pgbench -M prepared -v -C -r -P 1 -c 1600 -j 32 -T 1800 -h 192.168.100.14 -p 6432 -U odyssey odyssey -l
```

result:
number of clients（Odyssey workers） | latency average | latency stddev | initial connection time | tps(without initial connection time)
-- | -- | -- | -- | --
1600（64 worker） | 990.722 ms | 944.704 ms | 245.483 ms | 1613.680246
1600（32 worker） | 921.327 ms | 808.063 ms | 284.051 ms | 1735.556498
1600（16 worker） | 619.962 ms | 545.135 ms | 273.002 ms | 2579.800865
1600（8 worker） | 463.815 ms | 289.091 ms | 266.086 ms | 3448.534146
1600（4 worker） | 422.803 ms | 210.417 ms | 315.054 ms | 3782.470729
1600（2 worker） | 369.549 ms | 174.422 ms | 345.244 ms | 4326.389900
1600（1 worker） | 461.425 ms | 118.102 ms | 347.428 ms | 3464.309351

Regarding the above test results, I have the following questions, I hope you can help me answer:

1. I would like to know if the results I am getting are as expected?

2. Why does performance decrease with more workers?

3. What is the recommended setting for Odyssey workers on different specifications of hosts?

4. Compared with Pgbouncer, under what circumstances can Odyssey's multi-threaded performance be fully utilized?

Odyssey configuration:
```
pid_file "/tmp/odyssey.pid"
daemonize yes

unix_socket_dir "/tmp"
unix_socket_mode "0644"

log_file "/tmp/odyssey.log"
log_format "%p %t %l [%i %s] (%c) %m\n"

log_to_stdout no

log_syslog no
log_syslog_ident "odyssey"
log_syslog_facility "daemon"

log_debug no
log_config yes
log_session yes
log_query no
log_stats yes
stats_interval 60
log_stats_prom yes

workers 2
resolvers 1

readahead 8192

cache_coroutine 0

coroutine_stack_size 16

nodelay yes

keepalive 15
keepalive_keep_interval 75
keepalive_probes 9

keepalive_usr_timeout 0


listen {
	host "*"
	port 6432
	backlog 128
	compression yes
	tls "allow"
}


storage "postgres_server" {
	type "remote"
	host "localhost"
	port 5432
}

database "odyssey" {
	user "odyssey" {
		authentication "md5"

		storage "postgres_server"
    
		auth_query_db "postgres"
		auth_query_user "postgres"
		auth_query "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"

		log_debug yes

		pool "session"														
		pool_size 1600

		pool_timeout 0
		pool_ttl 0
		pool_discard yes
		pool_cancel yes
		pool_rollback yes
    
		quantiles "0.99,0.95,0.5"
		client_max 8000
  }
}

database "postgres" {
	user "postgres" {
		authentication "none"
		storage "postgres_server"
		
		pool "session"
		pool_routing "internal"

		log_debug yes
		pool_discard yes

		quantiles "0.99,0.95,0.5"
		client_max 107
	}
}


locks_dir "/tmp/odyssey"
graceful_die_on_errors yes
enable_online_restart no
bindwith_reuseport yes
```

**Comment by x4m** [comment]
Hi! Very interesting results!
As far as I can see time to connect decreases, but the pool is consuming resources from the database. Can you please re-run test with "SELECT 1;" instead of the default pgbench script?

**Comment by yanboer** [comment]
> Hi! Very interesting results! As far as I can see time to connect decreases, but the pool is consuming resources from the database. Can you please re-run test with "SELECT 1;" instead of the default pgbench script?


Thanks for the suggestion, I ran with 'SELECT 1;' instead of the pgbench default script and got the following results.

number of clients（Odyssey workers） | latency average | latency stddev | initial connection time | tps(without initial connection time)
-- | -- | -- | -- | --
1600（64 worker） | 131.537 ms | 421.963 ms | 261.263 ms | 12153.670079
1600（32 worker） | 131.674 ms | 403.728 ms | 312.730 ms | 12144.046721
1600（16 worker） | 117.027 ms | 311.336 ms | 282.305 ms | 13666.749276
1600（8 worker） | 11.860 ms | 59.467 ms | 280.055 ms | 134824.266533
1600（4 worker） | 9.063 ms | 5.420 ms | 319.935 ms | 176408.036127
1600（2 worker） | 18.398 ms | 9.578 ms | 316.186 ms | 86893.912601
1600（1 worker） | 51.383 ms | 33.432 ms | 367.106 ms | 31105.968837

**Comment by x4m** [comment]
Seems like somewhere between 4 and 8 workers are optimal for your setup. Does this match your expectations? You have 16 logical cores - hyperthreaded CPUs. 8 physical cores. Most (but not all) of the workload is concentrated on reconnecting.

One more thing that comes to my mind: measuring TPS without connection time doesn't seem to make sense with -C option - this option is specifically designed to stress reconnection.
BTW why do you stress unencrypted connections? Usually we use TLS...

**Comment by yanboer** [comment]
Thanks for your suggestion, I found this was my problem.

I installed PostgreSQL and Odyssey on the same host. During the test, PostgreSQL will preempt CPU resources, causing Odyssey to actually schedule less CPU than the host cores.

When I installed PostgreSQL and Odyssey on different hosts, I got the following conclusions:

number of clients（Odyssey workers） | latency average | latency stddev | average connection time | tps(including reconnection times)
-- | -- | -- | -- | --
1600（128 worker） | 82.112 ms | 70.100 ms | 2.552 ms | 9765.290244
1600（64 worker） | 80.969 ms | 70.934 ms | 2.507 ms | 9909.334465
1600（32 worker） | 80.567 ms | 71.728 ms | 2.477 ms | 9968.438329
1600（16 worker） | 80.366 ms | 72.218 ms | 2.425 ms | 10005.306256
1600（8 worker） | 79.734 ms | 72.368 ms | 2.412 ms | 10085.208119
1600（4 worker） | 83.706 ms | 68.106 ms | 2.540 ms | 9598.016439
1600（2 worker） | 98.129 ms | 61.705 ms | 2.978 ms | 8172.208916
1600（1 worker） | 145.787 ms | 83.315 ms | 4.436 ms | 5497.304217

The test results were as expected.

By the way, I did not use the -C parameter of pgbench in the previous test results, this is my mistake.

**Comment by yanboer** [comment]
> You can also try this tests on ARM machine now, as ARM arch is now supported in odyssey

Thank you very much, this is a good idea
