### ISSUE TITLE
Putin = Hitler

### ISSUE THREAD

**Issue by jh5pzj3p** [yandex/odyssey#422]
Stop the war!

**Comment by x4m** [comment]
I can neither fix this (rpm -e putin) nor document (putin zip file). I think your vandalism is counter-productive. Please report relevant technical issues.

**Comment by jh5pzj3p** [comment]
@x4m желаю чтобы ты поскрее узнал, что такое настоящий вандализм. твое молчание делает тебя соучастником приступления. ты раб, и поддерживаеш убийства в нашей стране.
вам скоро еще и интернет отлючат, вот тогда будешь пиздеть о "продуктивности" на локальном форуме "хуевый екатеринбург"

спокойной ночи, Андрюша. спи спокойно.
