### ISSUE TITLE
The WAR in Ukraine, russian attack and invasion! Please, see the truth.

### ISSUE THREAD

**Issue by ultraon** [yandex/odyssey#425]
Hello guys, I'm from Kharkiv city Ukraine. Just want to let you know, that it is the absolute truth, that the Russian military attacked my city on Feb 24th at about 4 am. My family and I had to evacuate immediately, from my hometown to the West.

I really appreciate it if you understand everything that is happening in the world and don't believe Russians News, they are crazy fraudsters and liars.

These are real photos and videos that I share, they destroyed already more than 400 civilian buildings (including civilian houses):

https://user-images.githubusercontent.com/6382537/157866173-28b13d3c-1c3b-4441-b8f5-0cb95e008fe2.MOV

![IMG_0749](https://user-images.githubusercontent.com/6382537/157866216-4308bb6a-652e-4416-be98-d71b07f975b9.JPG)
![IMG_0748](https://user-images.githubusercontent.com/6382537/157866239-f4bb0dd8-2d0c-40cb-8013-d0289eeda9d4.JPG)
![IMG_0744](https://user-images.githubusercontent.com/6382537/157866264-55d6c5c5-fb1b-4ff2-837f-f8d32f6e9262.JPG)
![IMG_0722](https://user-images.githubusercontent.com/6382537/157866301-f71a10af-e99d-41b8-b0ed-89ca4f3e7360.JPG)

This is Kharkiv center city (downtown):

https://user-images.githubusercontent.com/6382537/157866714-dbb14d3c-7adf-4c17-ba52-abdba0724d17.MP4

Mariupol maternity hospital:

https://user-images.githubusercontent.com/6382537/157866823-6f3e8f2c-cd80-426a-83a6-eee3d5fda6b1.MP4

And many many more :'-(

**Comment by ultraon** [comment]
И что касается реальных потерь российских солдатов, вот наша сводка:
![IMG_0780](https://user-images.githubusercontent.com/6382537/157871010-1df6f321-1627-4adb-9a6f-06d1fd597d90.JPG)

**Comment by juanpc2018** [comment]
#1. This is No place for that,
open a Telegram Channel... like everybody else.
#2. 
ask Zelinski Not to allow 30x US Biological weapon laboratory in Ukraine.
https://twitter.com/HanyHelaly1/status/1502413993910149124

you dont know what is to have 21x times Covid in your brain.
