### ISSUE TITLE
auth_query explanation

### ISSUE THREAD

**Issue by jurim76** [yandex/odyssey#468]
Please clarify how to use "auth_query" correctly, it's not clear from documentation how to use it properly.
I'm trying to migrate from pgbouncer to odyssey 1.3 and faced with some strange behaviour.
For example pgbouncer configuration auth block, where /etc/pgbouncer/userlist.txt contains svc_pgbouncer password

  auth_file = /etc/pgbouncer/userlist.txt
  auth_type = md5
  auth_query = SELECT uname, phash FROM pgbouncer.user_lookup($1)
  auth_user = pgbouncer

Odyssey doesn't support auth_file directive, how "auth_user" authenicated with storage and how to define password for "auth_user"? 
 storage_user "svc_pgbouncer" and storage_password "password"? In this case "storage user" mixed up with "auth_user", it's not clear for me.
 
 For pgbouncer you just could define database as "db1 = host=10.1.2.3 port=5432 dbname=testdb" and that's all, for odyssey you need to create complicated blocks like

  storage "test" {
      type "remote"
      host "testdb"
      port 5432
      tls "disable"
   }

 database default {
      user default {
        authentication "md5"
        password "md5****" (why? I want to use auth_query)
        auth_query "SELECT uname,phash FROM pgbouncer.user_lookup($1)"
        auth_query_db "postgres"
        auth_query_user "pgbouncer"
        storage "test"
        storage_user "pgbouncer" (?)
        storage_password "password" (?)
        pool "transaction" 

Ok, I just want to add one test database and I want use auth_query for all users by default
Something like this

database "test" {
  storage "test"
}

Failed, seems like I need to clone the whole block

  database "test" {
    user default (why? duplicates default user)
      authentication "md5" (why? duplicates default user)
      password "md5**" (why? I just want to use default user)
      storage "test" (why? duplicates default user)
  }

I've tried various combinations for auth_query and every time got the same error
psql: error: connection to server at "pgproxy" (172.16.0.41), port 5432 failed: ERROR:  odyssey: c7c1b337af8fd: failed to make auth query

**Comment by ilya-maltsev** [comment]
@jurim76 
by design, the auth_query function uses postgres user credentials on a target server to authenticate clients, so working auth_query must be:
"SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
and auth_query_user must have superuser permissions for execute this query
you can see the working config in https://github.com/yandex/odyssey/blob/master/docker/auth_query/config.conf.
and preparations for it
https://github.com/yandex/odyssey/blob/master/docker/bin/setup
Also you may use any custom db that contain clients logins & password hashes
As an alternative you can try using ldap authentication

**Comment by jurim76** [comment]
Could you please clarify some moments for me

storage "postgres_server" {
>         type "remote"
>         host "127.0.0.1"
>         port 5432
> }
>
> database "auth_query_db" {
>   user "auth_query_user_md5" {
>     authentication "md5"
>     auth_query "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
>     auth_query_user "postgres"
>     auth_query_db "postgres"
>     storage "postgres_server"
>     pool "session"
>   }
> }
>

   1. How "postgres" user authenticates with a storage server during
   auth_query? In the case of localhost it could be passwordless, but how to
   define a password for "auth_query_user", if the storage server has an
   external ip?
   2. Due to a security policy, I can not use postgres user for
   authentication, could I use a different user with a similar grant
   <https://www.2ndquadrant.com/en/blog/pg-phriday-securing-pgbouncer/> for
   "auth_query_user"?
   3. I've tried with postgres user from working config, but got the same
   error message, seems like odyssey doesn't perform auth_query for some
   reason and throws an error (odyssey debug shows only "PasswordMessage"
   string and no entries in postgresql log)

My config

>     storage "postgres_server" {
>       type "remote"
>       host "172.16.0.235"
>       port 5432
>     }
>
>     database "test" {
>       user default {
>         authentication "md5"
>         auth_query "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
>         auth_query_user "postgres"
>         auth_query_db "postgres"
>         storage "postgres_server"
>         storage_user "postgres"
>         storage_password "Abcd12345"
>         pool "transaction"
>         log_debug yes
>         log_query yes
>       }
>     }
>

On client side
> psql -h pgproxy -p 6432 -U testuser -W test

Odyssey log

> 8 2022-09-18T09:28:21Z info (startup) none Starting Odyssey
> 8 2022-09-18T09:28:21Z info [none none] (init) odyssey (git: 303fbaa
> release)
> 8 2022-09-18T09:28:21Z info [none none] (init)
> 8 2022-09-18T09:28:21Z info [none none] (init) using configuration file
> '/opt/odyssey.conf'
> 8 2022-09-18T09:28:21Z info [none none] (init)
> 8 2022-09-18T09:28:21Z info [none none] (server) listening on 0.0.0.0:6432
> 8 2022-09-18T09:28:21Z info [none none] (server) listening on [::]:6432
> 8 2022-09-18T09:28:46Z info [c6f0e842ba534 none] (startup) new client
> connection 10.244.138.125:60118
> 8 2022-09-18T09:28:46Z info [c6f0e842ba534 none] (startup) route
> 'test.testuser' to 'test.default_user'
> 8 2022-09-18T09:28:46Z debug [c6f0e842ba534 none] (auth) PasswordMessage
> 8 2022-09-18T09:28:46Z error [c6f0e842ba534 none] (auth) failed to make
> auth_query
> 8 2022-09-18T09:28:46Z info [c6f0e842ba534 none] (auth) ip
> '10.244.138.125' user 'test.testuser': host based authentication allowed

**Comment by ilya-maltsev** [comment]
@jurim76 
1. postgres authentificate auth_query_user with trust auth-method:
https://github.com/yandex/odyssey/blob/303fbaa73000dfdfc306083e9c81bd83d93d5fbe/docker/bin/setup#L28
password cannot be used for auth_query_user authentication

2. insert first line in your hba.conf (172.16.0.0/24 - its only for example, here must be ip of odyssey ):
host    all             auth_query_user            172.16.0.0/24         trust
execute on postgresql server:
SELECT pg_reload_conf();
CREATE USER "auth_query_user" WITH password 'test_pass';
ALTER  USER "auth_query_user" with superuser;
on the odyssey host try connect to postgres:
$ psql -h 172.16.0.235 -d postgres --user=auth_query_user
$ postgres=# SELECT usename, passwd FROM pg_shadow;

3. Perhaps you did not configure postgresql for host based auth-method

**Comment by jurim76** [comment]
Still got the same error "failed to make auth query"

odyssey binary was created from master branch with "make local_build"
command

> $ odyssey -V
> odyssey (git: 2053 303fbaa release)
>

I've created auth_query_user with superuser grants and added to pg_hba.conf

> host all auth_query_user 0.0.0.0/0 trust
>

Odyssey config

>     daemonize no
>     unix_socket_dir "/tmp"
>     unix_socket_mode "0644"
>     log_to_stdout yes
>     log_syslog no
>     log_debug yes
>     log_query yes
>     log_config yes
>     log_format "%p %t %l [%i %s] (%c) %m\n"
>     workers 1
>     resolvers 1
>
>     listen {
>       host "*"
>       port 6432
>       tls "disable"
>     }
>
>     storage "postgres_server" {
>       type "remote"
>       host "172.16.0.235"
>       port 5432
>     }
>
>     database "test" {
>       user default {
>         authentication "md5"
>         auth_query "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
>         auth_query_user "auth_query_user"
>         auth_query_db "postgres"
>         storage "postgres_server"
>         pool "transaction"
>         log_debug yes
>         log_query yes
>       }
>     }


Testing trust authentication:

> ***@***.***:/$ psql -h testdb -U auth_query_user -d postgres
> psql (14.4 (Debian 14.4-1.pgdg110+1), server 13.8 (Debian
> 13.8-1.pgdg110+1))
> Type "help" for help.
> postgres=# SELECT usename, passwd FROM pg_shadow WHERE usename='testuser';
>  usename  |               passwd
> ----------+-------------------------------------
>  testuser | md5ded772d336ed9c54ec6a9f6f2298068d
>

Testing testuser:

> ***@***.***:/$ psql -h testdb -U testuser -W -d test
> Password:
> psql (14.4 (Debian 14.4-1.pgdg110+1), server 13.8 (Debian
> 13.8-1.pgdg110+1))
> Type "help" for help.
> test=>
>

Testing odyssey auth_query:

> ***@***.***:/$ psql -h pgproxy -p 6432 -U testuser -W test
> Password:
> psql: error: connection to server at "pgproxy" (172.16.0.41), port 6432
> failed: ERROR:  odyssey: c31cfb65a3f93: failed to make auth query
>

Odyssey log

> 7 2022-09-18T15:04:54Z info [none none] (server) listening on 0.0.0.0:6432
> 7 2022-09-18T15:04:54Z info [none none] (server) listening on [::]:6432
> 7 2022-09-18T15:05:19Z info [c31cfb65a3f93 none] (startup) new client
> connection 10.244.138.125:41068
> 7 2022-09-18T15:05:19Z debug [none none] (routing) matched rule: test
> default_user with (null) routing type
> 7 2022-09-18T15:05:19Z info [c31cfb65a3f93 none] (startup) route
> 'test.testuser' to 'test.default_user'
> 7 2022-09-18T15:05:19Z debug [c31cfb65a3f93 none] (auth) PasswordMessage
> 7 2022-09-18T15:05:19Z debug [icc26b4808ae3b none] (auth_query) failed to
> route internal auth query client: OD_ROUTER_ERROR_NOT_FOUND
> 7 2022-09-18T15:05:19Z error [c31cfb65a3f93 none] (auth) failed to make
> auth_query
> 7 2022-09-18T15:05:19Z info [c31cfb65a3f93 none] (auth) ip
> '10.244.138.125' user 'test.testuser': host based authentication allowed
>

**Comment by ilya-maltsev** [comment]
@jurim76 

 7 2022-09-18T15:05:19Z debug [icc26b4808ae3b none] (auth_query) **failed to
 route internal auth query client**: OD_ROUTER_ERROR_NOT_FOUND
 that means you didn't add a route for auth_query internal routing
 
try with this odyssey config:
```
daemonize no
unix_socket_dir "/tmp"
unix_socket_mode "0644"
log_to_stdout yes
log_syslog no
log_debug yes
log_query yes
log_config yes
log_format "%p %t %l [%i %s] (%c) %m\n"
workers 1
resolvers 1

listen {
 host "*"
 port 6432
 tls "disable"
}

storage "postgres_server" {
 type "remote"
 host "172.16.0.235"
 port 5432
}

database "postgres" {
        user "auth_query_user" {
                authentication "none"
                pool_routing "internal"
                storage "postgres_server"
                pool "session"
        }
}

 database "test" {
   user default {
     authentication "md5"
     auth_query "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
     auth_query_user "auth_query_user"
     auth_query_db "postgres"
     storage "postgres_server"
     pool "transaction"
     log_debug yes
     log_query yes
   }
 }


```

**Comment by jurim76** [comment]
Thank you! It works finally.

Perhaps it's a good idea to update documentation with this information to
prevent unnecessary questions.
