### ISSUE TITLE
Odysseus crashes without issue description after connection LDAP user

### ISSUE THREAD

**Issue by skilyazhnev** [yandex/odyssey#478]
Hi!

We faced a problem when we build odyssey with LDAP lib (we build in Odessey docker-dev env)

We must increase `coroutine_stack_size` from 4 to 16 or odyssey fall with a `segment fault` error after an attempt to connect any LDAP user. 

And in odyssey-dev-ldap.conf you already did this. I guess Odyssey need some error notification or doc note about running odyssey with LDAP. 

Because we were only able to find Odyssey problem through tests and this can be tricky for new users using LDAP.

**Comment by x4m** [comment]
Hi! Yes, you are absolutely correct. LDAP routines needs more stack than typically Odyssey allocates. Please, send a PR with such a note that would simplify life for anyone following your route.
Thank you for letting us know!
