### ISSUE TITLE
core dump in transaction pooling mode

### ISSUE THREAD

**Issue by rzharkov** [yandex/odyssey#50]
Добрый день! В процессе замеров производительности с помощью pgbench программа аварийно завершилась.
Odyssey в transaction pooling режиме. Количество клиентских соединений в pgbench указано чуть больше ограничения pool_size. Тест (видимо) любой отличный от дефолтного tpcb-like

PostgreSQL 11.2-REL_11_STABLE/dadf9814d0

В odyssey.conf сделаны два изменения:

pool "session" => pool "transaction"
pool_size 0 => pool_size 10
 

**pgbench -c 15 test -S -T 3 -p 6432 -h localhost**

Лог:

> 26181 11 Mar 17:21:47.401 info [none none] (init) odyssey (git: 73f4f9e release)
> 26181 11 Mar 17:21:47.401 info [none none] (init) 
> 26181 11 Mar 17:21:47.401 info [none none] (init) using configuration file 'odyssey_my.conf'
> 26181 11 Mar 17:21:47.401 info [none none] (init) 
> 26181 11 Mar 17:21:47.401 info [none none] (config) daemonize            no
> 26181 11 Mar 17:21:47.401 info [none none] (config) priority             0
> 26181 11 Mar 17:21:47.401 info [none none] (config) unix_socket_dir      /tmp
> 26181 11 Mar 17:21:47.401 info [none none] (config) unix_socket_mode     0644
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_format           %p %t %l [%i %s] (%c) %m\n
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_to_stdout        yes
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_syslog           no
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_syslog_ident     odyssey
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_syslog_facility  daemon
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_debug            no
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_config           yes
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_session          yes
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_query            no
> 26181 11 Mar 17:21:47.401 info [none none] (config) log_stats            yes
> 26181 11 Mar 17:21:47.401 info [none none] (config) stats_interval       60
> 26181 11 Mar 17:21:47.401 info [none none] (config) readahead            8192
> 26181 11 Mar 17:21:47.401 info [none none] (config) nodelay              yes
> 26181 11 Mar 17:21:47.401 info [none none] (config) keepalive            7200
> 26181 11 Mar 17:21:47.401 info [none none] (config) cache_msg_gc_size    0
> 26181 11 Mar 17:21:47.401 info [none none] (config) cache_coroutine      0
> 26181 11 Mar 17:21:47.401 info [none none] (config) coroutine_stack_size 4
> 26181 11 Mar 17:21:47.401 info [none none] (config) workers              1
> 26181 11 Mar 17:21:47.401 info [none none] (config) resolvers            1
> 26181 11 Mar 17:21:47.401 info [none none] (config) 
> 26181 11 Mar 17:21:47.401 info [none none] (config) listen
> 26181 11 Mar 17:21:47.401 info [none none] (config)   host          *
> 26181 11 Mar 17:21:47.401 info [none none] (config)   port          6432
> 26181 11 Mar 17:21:47.401 info [none none] (config)   backlog       128
> 26181 11 Mar 17:21:47.401 info [none none] (config) 
> 26181 11 Mar 17:21:47.401 info [none none] (rules) <default.default>
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   authentication   none
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   pool             transaction
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   pool_size        10
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   pool_timeout     0
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   pool_ttl         60
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   pool_discard     no
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   pool_cancel      yes
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   pool_rollback    yes
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   client_fwd_error yes
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   storage          postgres_server
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   type             remote
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   host             localhost
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   port             5432
> 26181 11 Mar 17:21:47.401 info [none none] (rules)   log_debug        no
> 26181 11 Mar 17:21:47.401 info [none none] (rules) 
> 26181 11 Mar 17:21:47.404 info [none none] (server) listening on 0.0.0.0:6432
> 26181 11 Mar 17:21:47.404 info [none none] (server) listening on [::]:6432
> 26181 11 Mar 17:22:46.681 info [none none] (stats) system worker: msg (1 allocated, 0 cached, 1 freed, 0 cache_size), coroutines (5 active, 0 cached)
> 26181 11 Mar 17:22:46.681 info [none none] (stats) clients 0
> 26181 11 Mar 17:22:46.681 info [none none] (stats) worker[0]: msg (2 allocated, 0 cached, 1 freed, 0 cache_size), coroutines (5 active, 0 cached), clients_processed: 0
> 26181 11 Mar 17:23:07.317 info [c2f8cc345ed53 none] (startup) new client connection [::1]:49780
> 26181 11 Mar 17:23:07.317 info [c2f8cc345ed53 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.318 info [c2f8cc345ed53 s332b886806d6] (setup) new server connection localhost:5432 (connect time: 608 usec, resolve time: 544 usec)
> 26181 11 Mar 17:23:07.320 info [c2f8cc345ed53 none] (setup) login time: 3384 microseconds
> 26181 11 Mar 17:23:07.321 info [c2f8cc345ed53 sa13a8214eff1] (main) new server connection localhost:5432 (connect time: 349 usec, resolve time: 262 usec)
> 26181 11 Mar 17:23:07.342 info [c2f8cc345ed53 sa13a8214eff1] (main) client disconnected
> 26181 11 Mar 17:23:07.342 info [c227ee838737c none] (startup) new client connection [::1]:49786
> 26181 11 Mar 17:23:07.342 info [c227ee838737c none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.342 info [c227ee838737c none] (setup) login time: 208 microseconds
> 26181 11 Mar 17:23:07.343 info [c9b28405c8109 none] (startup) new client connection [::1]:49788
> 26181 11 Mar 17:23:07.343 info [c9b28405c8109 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.343 info [c9b28405c8109 none] (setup) login time: 189 microseconds
> 26181 11 Mar 17:23:07.343 info [c9127367f50df none] (startup) new client connection [::1]:49790
> 26181 11 Mar 17:23:07.343 info [c9127367f50df none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.343 info [c9127367f50df none] (setup) login time: 139 microseconds
> 26181 11 Mar 17:23:07.344 info [cfce2b65cf9f6 none] (startup) new client connection [::1]:49792
> 26181 11 Mar 17:23:07.344 info [cfce2b65cf9f6 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.344 info [cfce2b65cf9f6 none] (setup) login time: 168 microseconds
> 26181 11 Mar 17:23:07.344 info [cc362a057cb0e none] (startup) new client connection [::1]:49794
> 26181 11 Mar 17:23:07.344 info [cc362a057cb0e none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.344 info [cc362a057cb0e none] (setup) login time: 101 microseconds
> 26181 11 Mar 17:23:07.345 info [c8429b060eedc none] (startup) new client connection [::1]:49796
> 26181 11 Mar 17:23:07.345 info [c8429b060eedc none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.345 info [c8429b060eedc none] (setup) login time: 131 microseconds
> 26181 11 Mar 17:23:07.345 info [c31247477cad7 none] (startup) new client connection [::1]:49798
> 26181 11 Mar 17:23:07.345 info [c31247477cad7 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.345 info [c31247477cad7 none] (setup) login time: 98 microseconds
> 26181 11 Mar 17:23:07.346 info [c63b63e69f695 none] (startup) new client connection [::1]:49800
> 26181 11 Mar 17:23:07.346 info [c63b63e69f695 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.346 info [c63b63e69f695 none] (setup) login time: 101 microseconds
> 26181 11 Mar 17:23:07.346 info [c2255f17a8280 none] (startup) new client connection [::1]:49802
> 26181 11 Mar 17:23:07.346 info [c2255f17a8280 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.346 info [c2255f17a8280 none] (setup) login time: 99 microseconds
> 26181 11 Mar 17:23:07.347 info [c5bb447108ac0 none] (startup) new client connection [::1]:49804
> 26181 11 Mar 17:23:07.347 info [c5bb447108ac0 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.347 info [c5bb447108ac0 none] (setup) login time: 103 microseconds
> 26181 11 Mar 17:23:07.347 info [ce3ee0906297c none] (startup) new client connection [::1]:49806
> 26181 11 Mar 17:23:07.347 info [ce3ee0906297c none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.347 info [ce3ee0906297c none] (setup) login time: 100 microseconds
> 26181 11 Mar 17:23:07.348 info [c942db56b0667 none] (startup) new client connection [::1]:49808
> 26181 11 Mar 17:23:07.348 info [c942db56b0667 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.348 info [c942db56b0667 none] (setup) login time: 102 microseconds
> 26181 11 Mar 17:23:07.348 info [ca44f2500c367 none] (startup) new client connection [::1]:49810
> 26181 11 Mar 17:23:07.348 info [ca44f2500c367 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.348 info [ca44f2500c367 none] (setup) login time: 101 microseconds
> 26181 11 Mar 17:23:07.349 info [cfc5ca44bcde5 none] (startup) new client connection [::1]:49812
> 26181 11 Mar 17:23:07.349 info [cfc5ca44bcde5 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.349 info [cfc5ca44bcde5 none] (setup) login time: 112 microseconds
> 26181 11 Mar 17:23:07.349 info [cefc20d7419c2 none] (startup) new client connection [::1]:49814
> 26181 11 Mar 17:23:07.349 info [cefc20d7419c2 none] (startup) route 'test.roman' to 'default.default'
> 26181 11 Mar 17:23:07.349 info [cefc20d7419c2 none] (setup) login time: 101 microseconds
> 26181 11 Mar 17:23:07.350 info [c9b28405c8109 s586ce74f8ad1] (main) new server connection localhost:5432 (connect time: 330 usec, resolve time: 249 usec)
> 26181 11 Mar 17:23:07.350 info [c9127367f50df sc5d7533fc9f0] (main) new server connection localhost:5432 (connect time: 436 usec, resolve time: 353 usec)
> 26181 11 Mar 17:23:07.350 info [cfce2b65cf9f6 secc8e04a91bf] (main) new server connection localhost:5432 (connect time: 513 usec, resolve time: 436 usec)
> 26181 11 Mar 17:23:07.350 info [cc362a057cb0e s57be52777644] (main) new server connection localhost:5432 (connect time: 508 usec, resolve time: 416 usec)
> 26181 11 Mar 17:23:07.350 info [c8429b060eedc sc3d8b64963f2] (main) new server connection localhost:5432 (connect time: 616 usec, resolve time: 508 usec)
> 26181 11 Mar 17:23:07.351 info [c31247477cad7 s5e873a4f1fce] (main) new server connection localhost:5432 (connect time: 710 usec, resolve time: 616 usec)
> 26181 11 Mar 17:23:07.351 info [c63b63e69f695 s9c7ac15e500c] (main) new server connection localhost:5432 (connect time: 940 usec, resolve time: 710 usec)
> 26181 11 Mar 17:23:07.351 info [c2255f17a8280 s17bfb8658ef7] (main) new server connection localhost:5432 (connect time: 940 usec, resolve time: 710 usec)
> 26181 11 Mar 17:23:07.351 info [c5bb447108ac0 s715a7f77370a] (main) new server connection localhost:5432 (connect time: 1007 usec, resolve time: 919 usec)
> *** Error in `./build/sources/odyssey': free(): invalid pointer: 0x00007f2090003c08 ***
> ======= Backtrace: =========
> /lib64/libc.so.6(+0x81489)[0x7f2098374489]
> ./build/sources/odyssey(od_router_attach+0x113)[0x4111c3]
> ./build/sources/odyssey[0x423679]
> ./build/sources/odyssey(od_frontend+0x2112)[0x4268a2]
> ./build/sources/odyssey[0x4315d0]
> ./build/sources/odyssey[0x4323d9]
> ======= Memory map: ========
> 00400000-0043d000 r-xp 00000000 fd:00 5157276                            /home/roman/git/odyssey/build/sources/odyssey
> 0063c000-0063d000 r--p 0003c000 fd:00 5157276                            /home/roman/git/odyssey/build/sources/odyssey
> 0063d000-0063e000 rw-p 0003d000 fd:00 5157276                            /home/roman/git/odyssey/build/sources/odyssey
> 00f74000-00fb7000 rw-p 00000000 00:00 0                                  [heap]
> 7f2088000000-7f2088021000 rw-p 00000000 00:00 0 
> 7f2088021000-7f208c000000 ---p 00000000 00:00 0 
> 7f2090000000-7f2090068000 rw-p 00000000 00:00 0 
> 7f2090068000-7f2094000000 ---p 00000000 00:00 0 
> 7f2096891000-7f20968a6000 r-xp 00000000 fd:00 518806                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
> 7f20968a6000-7f2096aa5000 ---p 00015000 fd:00 518806                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
> 7f2096aa5000-7f2096aa6000 r--p 00014000 fd:00 518806                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
> 7f2096aa6000-7f2096aa7000 rw-p 00015000 fd:00 518806                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
> 7f2096aa7000-7f2096ab3000 r-xp 00000000 fd:00 8739                       /usr/lib64/libnss_files-2.17.so
> 7f2096ab3000-7f2096cb2000 ---p 0000c000 fd:00 8739                       /usr/lib64/libnss_files-2.17.so
> 7f2096cb2000-7f2096cb3000 r--p 0000b000 fd:00 8739                       /usr/lib64/libnss_files-2.17.so
> 7f2096cb3000-7f2096cb4000 rw-p 0000c000 fd:00 8739                       /usr/lib64/libnss_files-2.17.so
> 7f2096cb4000-7f2096cba000 rw-p 00000000 00:00 0 
> 7f2096cba000-7f2096d1a000 r-xp 00000000 fd:00 8877                       /usr/lib64/libpcre.so.1.2.0
> 7f2096d1a000-7f2096f1a000 ---p 00060000 fd:00 8877                       /usr/lib64/libpcre.so.1.2.0
> 7f2096f1a000-7f2096f1b000 r--p 00060000 fd:00 8877                       /usr/lib64/libpcre.so.1.2.0
> 7f2096f1b000-7f2096f1c000 rw-p 00061000 fd:00 8877                       /usr/lib64/libpcre.so.1.2.0
> 7f2096f1c000-7f2096f40000 r-xp 00000000 fd:00 8766                       /usr/lib64/libselinux.so.1
> 7f2096f40000-7f209713f000 ---p 00024000 fd:00 8766                       /usr/lib64/libselinux.so.1
> 7f209713f000-7f2097140000 r--p 00023000 fd:00 8766                       /usr/lib64/libselinux.so.1
> 7f2097140000-7f2097141000 rw-p 00024000 fd:00 8766                       /usr/lib64/libselinux.so.1
> 7f2097141000-7f2097143000 rw-p 00000000 00:00 0 
> 7f2097143000-7f2097159000 r-xp 00000000 fd:00 8749                       /usr/lib64/libresolv-2.17.so
> 7f2097159000-7f2097358000 ---p 00016000 fd:00 8749                       /usr/lib64/libresolv-2.17.so
> 7f2097358000-7f2097359000 r--p 00015000 fd:00 8749                       /usr/lib64/libresolv-2.17.so
> 7f2097359000-7f209735a000 rw-p 00016000 fd:00 8749                       /usr/lib64/libresolv-2.17.so
> 7f209735a000-7f209735c000 rw-p 00000000 00:00 0 
> 7f209735c000-7f209735f000 r-xp 00000000 fd:00 8909                       /usr/lib64/libkeyutils.so.1.5
> 7f209735f000-7f209755e000 ---p 00003000 fd:00 8909                       /usr/lib64/libkeyutils.so.1.5
> 7f209755e000-7f209755f000 r--p 00002000 fd:00 8909                       /usr/lib64/libkeyutils.so.1.5
> 7f209755f000-7f2097560000 rw-p 00003000 fd:00 8909                       /usr/lib64/libkeyutils.so.1.5
> 7f2097560000-7f209756e000 r-xp 00000000 fd:00 9000                       /usr/lib64/libkrb5support.so.0.1
> 7f209756e000-7f209776e000 ---p 0000e000 fd:00 9000                       /usr/lib64/libkrb5support.so.0.1
> 7f209776e000-7f209776f000 r--p 0000e000 fd:00 9000                       /usr/lib64/libkrb5support.so.0.1
> 7f209776f000-7f2097770000 rw-p 0000f000 fd:00 9000                       /usr/lib64/libkrb5support.so.0.1
> 7f2097770000-7f2097785000 r-xp 00000000 fd:00 526664                     /usr/lib64/libz.so.1.2.7
> 7f2097785000-7f2097984000 ---p 00015000 fd:00 526664                     /usr/lib64/libz.so.1.2.7
> 7f2097984000-7f2097985000 r--p 00014000 fd:00 526664                     /usr/lib64/libz.so.1.2.7
> 7f2097985000-7f2097986000 rw-p 00015000 fd:00 526664                     /usr/lib64/libz.so.1.2.7
> 7f2097986000-7f20979b7000 r-xp 00000000 fd:00 8992                       /usr/lib64/libk5crypto.so.3.1
> 7f20979b7000-7f2097bb6000 ---p 00031000 fd:00 8992                       /usr/lib64/libk5crypto.so.3.1
> 7f2097bb6000-7f2097bb8000 r--p 00030000 fd:00 8992                       /usr/lib64/libk5crypto.so.3.1
> 7f2097bb8000-7f2097bb9000 rw-p 00032000 fd:00 8992                       /usr/lib64/libk5crypto.so.3.1
> 7f2097bb9000-7f2097bbc000 r-xp 00000000 fd:00 8805                       /usr/lib64/libcom_err.so.2.1
> 7f2097bbc000-7f2097dbb000 ---p 00003000 fd:00 8805                       /usr/lib64/libcom_err.so.2.1
> 7f2097dbb000-7f2097dbc000 r--p 00002000 fd:00 8805                       /usr/lib64/libcom_err.so.2.1
> 7f2097dbc000-7f2097dbd000 rw-p 00003000 fd:00 8805                       /usr/lib64/libcom_err.so.2.1
> 7f2097dbd000-7f2097e96000 r-xp 00000000 fd:00 8998                       /usr/lib64/libkrb5.so.3.3
> 7f2097e96000-7f2098095000 ---p 000d9000 fd:00 8998                       /usr/lib64/libkrb5.so.3.3
> 7f2098095000-7f20980a3000 r--p 000d8000 fd:00 8998                       /usr/lib64/libkrb5.so.3.3
> 7f20980a3000-7f20980a6000 rw-p 000e6000 fd:00 8998                       /usr/lib64/libkrb5.so.3.3
> 7f20980a6000-7f20980f0000 r-xp 00000000 fd:00 8988                       /usr/lib64/libgssapi_krb5.so.2.2
> 7f20980f0000-7f20982f0000 ---p 0004a000 fd:00 8988                       /usr/lib64/libgssapi_krb5.so.2.2
> 7f20982f0000-7f20982f1000 r--p 0004a000 fd:00 8988                       /usr/lib64/libgssapi_krb5.so.2.2
> 7f20982f1000-7f20982f3000 rw-p 0004b000 fd:00 8988                       /usr/lib64/libgssapi_krb5.so.2.2
> 7f20982f3000-7f20984b5000 r-xp 00000000 fd:00 8721                       /usr/lib64/libc-2.17.so
> 7f20984b5000-7f20986b5000 ---p 001c2000 fd:00 8721                       /usr/lib64/libc-2.17.so
> 7f20986b5000-7f20986b9000 r--p 001c2000 fd:00 8721                       /usr/lib64/libc-2.17.so
> 7f20986b9000-7f20986bb000 rw-p 001c6000 fd:00 8721                       /usr/lib64/libc-2.17.soАварийный останов (core dumped)

**Comment by x4m** [comment]
Hi! Thanks for your report!
I was able to reproduce this, this bug certainly, will look into this!

**Comment by pmwkaa** [comment]
This commit: https://github.com/yandex/odyssey/commit/af015839b03f30260c75d8f565521910c0694ed6 should fix it, please try again :)

**Comment by rzharkov** [comment]
Спасибо, обязательно попробую в ближайшие сутки.

**Comment by rzharkov** [comment]
Работает, спасибо!
