### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by rzharkov** [yandex/odyssey#52]
Добрый день!
Продолжаем тестировать ваш пулер.
Во время серии select only тестов pgbench пришёл oom killer:
[8821049.263349] Out of memory: Kill process 11181 (odyssey) score 966 or sacrifice child
[8821049.263537] Killed process 11181 (odyssey) total-vm:49845424kB, anon-rss:47964152kB, file-rss:0kB

Серия такая: запуск Одиссея с pool_size = 16 и workers 4. Логирование минимальное.
Дальше идёт последовательный запуск pgbench -S -T 300 с числом подключений от 100 до 1000 и шагом 50. Вот в конце последнего шага произошла данная ошибка.
Также наблюдаем снижение производительности при увеличении количества подключений.

Всё ли мы правильно настроили?
[odyssey-16-4.txt](https://github.com/yandex/odyssey/files/2982198/odyssey-16-4.txt)

Промежуточные результаты тестирования на графиках:
![1552838409 svg](https://user-images.githubusercontent.com/43462737/54589877-72cb9480-4a59-11e9-86af-25afc09cf47c.png)
![1552963850 svg](https://user-images.githubusercontent.com/43462737/54589878-72cb9480-4a59-11e9-89c1-3b92bf6f5c0e.png)

**Comment by x4m** [comment]
Hello!
Perf degradation with RW-test is expected (due to PROCARRAY and other structures contention), while we want to do it be smaller for RO case (which should be optimized out by pooler).

Settings look sane. I will look more into details of OOM, I did not observe memory pressure before, but this seems very important.

Добрый день!
Деградация на RW ожидаема, а вот от деградации на RO хотелось бы избавится, да.
Настройки не выглядят подозрительно, ООМ посмотрим, такое надо обязательно чинить.

**Comment by rzharkov** [comment]
Добрый день!
В сравнении с другими пулерами деградация RW слишком большая. Подозреваем, что причина как раз в утечках памяти.

**Comment by x4m** [comment]
@rzharkov 
Hi! We have fixed several memory leaks. Thanks for the report!

Добрый день!
Мы починили несколько утечек, спасибо что сообщили. Над масштабируемостью ещё работаем.

**Comment by rzharkov** [comment]
Спасибо!
На первый взгляд не воспроизвелось, продолжаем бенчмарки.

**Comment by rzharkov** [comment]
Проблема не повторилась больше.

**Comment by x4m** [comment]
Can you please share benchmark results?
We definitely want to improve Odyssey and external benchmarks are very helpful.

Если у вас будет возможность, пожалуйста, поделитесь результатами бенчмарков. Нам нужно непоправимо улучшать Одисея, и тут внешний взгляд очень полезен.

**Comment by rzharkov** [comment]
Добрый день!
Вот такие результаты получились на нашем стенде:

![1553857559 svg](https://user-images.githubusercontent.com/43462737/55314259-fb075c00-5493-11e9-8c01-74aeb1003679.png)
![1553909001 svg](https://user-images.githubusercontent.com/43462737/55314260-fb075c00-5493-11e9-8f87-ee1fb4465019.png)

![1552464644 svg](https://user-images.githubusercontent.com/43462737/55314781-1757c880-5495-11e9-8e92-e70cbb9607cf.png)
![1552548615 svg](https://user-images.githubusercontent.com/43462737/55314782-1757c880-5495-11e9-960b-73161738531b.png)

![s1552622632 svg](https://user-images.githubusercontent.com/43462737/55315244-28eda000-5496-11e9-8c87-8d74e3ed17dc.png)
![t1552622632 svg](https://user-images.githubusercontent.com/43462737/55315246-28eda000-5496-11e9-9883-c69de70a8940.png)

**Comment by rzharkov** [comment]
О, собственно вот тут сравнение есть: https://github.com/postgrespro/postgresql.builtin_pool/wiki/Benchmarking-connection-poolers

**Comment by x4m** [comment]
Cool, thanks!
Круто, спасибо.

**Comment by flionet89** [comment]
Добрый день! Я столкнулся с проблемой утечки памяти. Установил Odyssey и пустил через него все микро сервисы что были. Это порядка 100 подов. В итоге odyssey не высвобождает память.
Использую конфиг:

[conf yandex.txt](https://github.com/yandex/odyssey/files/8161934/conf.yandex.txt)

График вот такой: 
![image](https://user-images.githubusercontent.com/54624114/156179123-ac41a1c3-0bc8-4f62-a3c7-6457fbc9c301.png)

В логе вот такое вот сообщение:
2022-02-21T16:50:34Z info [none none] (stats) worker[0]: msg (1155885834 allocated, 0 cached, 1195379527 freed, 0 cache_size), coroutines (640 active, 0 cached), clients_processed: 42986368

Подскажите в чем может быть проблема?

**Comment by x4m** [comment]
To English readers: this is a report about a memory leak in Russian.

Руслан, спасибо за сообщение. Расскажите поподробнее про использование. Из конфига я так понял что вы используете auth_query,  да?
Мы знаем об одной утечке при пробросе некоторых ошибок, но в auth_query не видели утечки... Есть ли в логах сообщения о пробросе FATAL ошибок?

**Comment by flionet89** [comment]
Нет, Fatal ошибок нет. Однако память все время растет. При чем не важно есть подключения к odyssey или нет.

**Comment by flionet89** [comment]
Что может так загружать память? Скажите где хранит свою статистику Console?
