### ISSUE TITLE
Plan for a new release ?

### ISSUE THREAD

**Issue by vrenaville** [yandex/odyssey#524]
Hello,

Do you plan to make a new release of odyssey soon ?

Thanks for your work

Vincent

**Comment by x4m** [comment]
Hello Vincent,

Yes, definietly, we've got plenty of new features. But we need to fix #487 and several memory leaks. And this stuff is not diagnosed yet...

**Comment by vrenaville** [comment]
Thanks for your quick answer (and apologize for my late respond  ), I will wait for it.

Vincent
