### ISSUE TITLE
CPU overhead

### ISSUE THREAD

**Issue by uspen** [yandex/odyssey#58]
Привет! Спасибо за отличный продукт!

Провожу тестирование. Если количество клиентов больше чем pool_size (pool_mode: transaction), то odyssey съедает все время CPU, разрешенное в workers

Hello! Thanks for the great product!

I spend testing. If the number of clients is greater than pool_size (pool_mode: transaction), then odyssey eats up all the CPU time allowed in workers.

**Comment by x4m** [comment]
Hi! Yes, pool size limit seems suboptimal to me too, I'll look into this. We usually do not use size-limited pools, but this functionality should work.

Привет! Да, что-то с pool_size не так, я поисследую вопрос. У себя мы не пользуемся ограниченными пулами, но чинить, безусловно, надо.

**Comment by pmwkaa** [comment]
@uspen Hey, please check out the latest master branch update, CPU usage should be reduced now

**Comment by uspen** [comment]
Yes, all good! Thank you!
