### ISSUE TITLE
Possible to kill the Odyssey Process via Telnet

### ISSUE THREAD

**Issue by josiahhaswell** [yandex/odyssey#59]
It's possible to telnet into Odyssey and kill the process via Telnet

Steps to reproduce:

- Start odyssey listening on port `<port>` (any config will do) `odyssey myconfig`
- Telnet into odyssey `telnet localhost <port>`
- Hit `ctrl+c`

Expected behavior:

Telnet processes ctrl+c

Actual behavior:

Odyssey process killed

**Comment by pmwkaa** [comment]
Please try again, this change https://github.com/yandex/odyssey/commit/a3f55f4f219c5aac6832d107b5c0afa8c831ba81 should fix the problem

**Comment by x4m** [comment]
I think it's fixed.
