### ISSUE TITLE
Build error on Ubuntu 19.04

### ISSUE THREAD

**Issue by ergo70** [yandex/odyssey#67]
I followed the build instructions but get the following error in the 'make' phase:

In file included from /odyssey/test/machinarium/test_sleeplock.c:3:
/odyssey/third_party/machinarium/sources/machinarium_private.h:44:10: fatal error: build.h: No such file or directory
 #include "build.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [test/CMakeFiles/odyssey_test.dir/build.make:427: test/CMakeFiles/odyssey_test.dir/machinarium/test_sleeplock.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:253: test/CMakeFiles/odyssey_test.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by x4m** [comment]
Hi! Thanks for reporting!
I've fixed this, now you can build according to same instruction.
