### ISSUE TITLE
Document the supported architecutres

### ISSUE THREAD

**Issue by iv-m** [yandex/odyssey#7]
As far as I understood, machinarium (and thus, oddysey) currently support only x86 and x86_64 architectures. While this is totally fine, and strict portability limitations are to be expected from any software that implements or uses coroutines, it would be helpful if this was documented somewhere, not just in the `#error` directive in `context.c`.

By the way, are there any plans for, and what is your general attitude to possible arm or mips ports?

**Comment by pmwkaa** [comment]
Yes, sorry. I've made a note about it. We don't have plans for it for the moment, but generally there should be not a problem to support it I guess.
