### ISSUE TITLE
Build error on Fedora 28

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [yandex/odyssey#8]
Hello,

I am using Fedora 28 (not Rawhide). I tried to build odyssey project, but got compile errors:

https://pastebin.com/vcWWf54f

`home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c: В функции «mm_tlsio_ctrl_cb»:
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:127:12: ошибка: dereferencing pointer to incomplete type «BIO» {aka «struct bio_st»}
   ret = bio->shutdown;
            ^~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c: На верхнем уровне:
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:147:1: ошибка: переменная «mm_tlsio_method» инициализирована, хотя имеет неполный тип
 static BIO_METHOD mm_tlsio_method =
 ^~~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:149:3: ошибка: «BIO_METHOD» {aka «struct bio_method_st»} не содержит элемента с именем «type»
  .type   = BIO_TYPE_MEM,
   ^~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:149:12: предупреждение: избыточные элементы в инициализаторе структуры
  .type   = BIO_TYPE_MEM,
            ^~~~~~~~~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:149:12: замечание: (где-то рядом с инициализацией для «mm_tlsio_method»)
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:150:3: ошибка: «BIO_METHOD» {aka «struct bio_method_st»} не содержит элемента с именем «name»
  .name   = "machinarium",
   ^~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:150:12: предупреждение: избыточные элементы в инициализаторе структуры
  .name   = "machinarium",
            ^~~~~~~~~~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:150:12: замечание: (где-то рядом с инициализацией для «mm_tlsio_method»)
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:151:3: ошибка: «BIO_METHOD» {aka «struct bio_method_st»} не содержит элемента с именем «bwrite»
  .bwrite = mm_tlsio_write_cb,
   ^~~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:151:12: предупреждение: избыточные элементы в инициализаторе структуры
  .bwrite = mm_tlsio_write_cb,
            ^~~~~~~~~~~~~~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:151:12: замечание: (где-то рядом с инициализацией для «mm_tlsio_method»)
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:152:3: ошибка: «BIO_METHOD» {aka «struct bio_method_st»} не содержит элемента с именем «bread»
  .bread  = mm_tlsio_read_cb,
   ^~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:152:12: предупреждение: избыточные элементы в инициализаторе структуры
  .bread  = mm_tlsio_read_cb,
            ^~~~~~~~~~~~~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:152:12: замечание: (где-то рядом с инициализацией для «mm_tlsio_method»)
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:153:3: ошибка: «BIO_METHOD» {aka «struct bio_method_st»} не содержит элемента с именем «ctrl»
  .ctrl   = mm_tlsio_ctrl_cb
   ^~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:153:12: предупреждение: избыточные элементы в инициализаторе структуры
  .ctrl   = mm_tlsio_ctrl_cb
            ^~~~~~~~~~~~~~~~
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:153:12: замечание: (где-то рядом с инициализацией для «mm_tlsio_method»)
/home/zamazan4ik/OpenSource/odyssey/build/third_party/machinarium/sources/tls_io.c:147:19: ошибка: размер «mm_tlsio_method» в памяти неизвестен
 static BIO_METHOD mm_tlsio_method =
                   ^~~~~~~~~~~~~~~
gmake[5]: *** [sources/CMakeFiles/machine_library_static.dir/build.make:362: sources/CMakeFiles/machine_library_static.dir/tls_io.c.o] Ошибка 1
gmake[4]: *** [CMakeFiles/Makefile2:86: sources/CMakeFiles/machine_library_static.dir/all] Ошибка 2
gmake[3]: *** [Makefile:84: all] Ошибка 2
make[2]: *** [CMakeFiles/libmachinarium.dir/build.make:64: third_party/machinarium/sources/libmachinarium.a] Ошибка 2
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/libmachinarium.dir/all] Ошибка 2
make: *** [Makefile:84: all] Ошибка 2`

I have used gcc 8.1.1, cmake 3.11.2, openssl-devel-1:1.1.0h-3.

My build steps are identical to provided by this repo.

I think it's about openssl-devel package version, but I am not sure.

**Comment by pmwkaa** [comment]
Yes, Sorry for confusion. Currently Odyssey requires openssl < 1.1. I've just made a small note about it in Readme.

**Comment by maksm90** [comment]
AFAIC the problem is in incompatible program interface in different versions of openssl library.

@pmwkaa what will be your decision to resolve this issue: use the separate branch for new openssl API or add conditional macros to provide separate implementations of conflicting code blocks or something else?

**Comment by pmwkaa** [comment]
I guess the only viable option here is to hide it under macros in future, because this will make less pain for users

**Comment by pmwkaa** [comment]
Should work now with latest OpenSSL. https://github.com/yandex/odyssey/commit/7e636b9139ce746037255061562b2f0caf602f31

**Comment by ZaMaZaN4iK** [comment]
Thank you a lot. I'll test it ASAP.

**Comment by davidfetter** [comment]
Should this issue be closed?
